language: objective-c
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3
xcode_project: Loop.xcodeproj
xcode_scheme: Loop
before_script:
    - carthage bootstrap
script:
    - xctool -project Loop.xcodeproj -scheme LoopTests -sdk iphonesimulator9.3 test
